spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    root: INFO
    com.ecommerce.user: TRACE
#  file:
#    name: logs/app.log