#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: product-service
#          uri: lb://PRODUCT-SERVICE
#          predicates:
#            - Path=/products/**
#          filters:
#            - "RewritePath=/products(?<segment>/?.*),/api/products${segment}"
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/users/**
#          filters:
#            - "RewritePath=/users(?<segment>/?.*),/api/users${segment}"
#        - id: order-service
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/orders/**, /cart/**
#          filters:
#            - "RewritePath=/(?<segment>.*),/api/${segment}"
#        - id: eureka-service
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/main
#          filters:
#            - SetPath=/
#        - id: eureka-server-static
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/**

server:
  port: 8080

#logging:
#  level:
#    root: info
#    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
#    org.springframework.cloud.gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCall: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationThreshold: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based
    instances:
      productBreaker:
        baseConfig: default
      userBreaker:
        baseConfig: default
      orderBreaker:
        baseConfig: default

#Security
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/ecom-app